version: "3.0"

expectations:
  population_size: 1000

actions:
  extract_ctv3_dictionary:
    run: >
      sqlrunner:latest
        --output output/ctv3_dictionary.csv
        analysis/extract_ctv3_dictionary.sql
    outputs:
      moderately_sensitive:
        rows: output/ctv3_dictionary.csv

  gzip_ctv3_dictionary:
    run: python:latest gzip output/ctv3_dictionary.csv
    needs: [extract_ctv3_dictionary]
    outputs:
      moderately_sensitive:
        gz_file: output/ctv3_dictionary.csv.gz

  extract_ctv3_hierarchy:
    run: >
      sqlrunner:latest
        --output output/ctv3_hierarchy.csv
        analysis/extract_ctv3_hierarchy.sql
    outputs:
      moderately_sensitive:
        rows: output/ctv3_hierarchy.csv
  
  gzip_ctv3_hierarchy:
    run: python:latest gzip output/ctv3_hierarchy.csv
    needs: [extract_ctv3_hierarchy]
    outputs:
      moderately_sensitive:
        gz_file: output/ctv3_hierarchy.csv.gz

  check_ctv3_events:
    run: >
      sqlrunner:latest
        --output output/coded_events_with_missing_ctv3_codes.csv
        analysis/check_ctv3_events.sql
    outputs:
      highly_sensitive:
        rows: output/coded_events_with_missing_ctv3_codes.csv
